version: '3'
services:
  spring-api:
    image: emptyvessel/spring-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
