name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and push Docker image
      run: |
        docker-compose build
    - name: Deploy Docker containers
      run: |
        docker-compose up -d
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        ssh-keyscan -t rsa 83.147.247.41 >> ~/.ssh/known_hosts

    - name: Deploy to production
      run: |
        ssh -o StrictHostKeyChecking=no git@github.com root@83.147.247.41 'cd lyftzeigen-spring-api/ && docker-compose pull && docker-compose up -d'