name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build and push Docker image
      run: |
        docker-compose build
    - name: Deploy Docker containers
      run: |
        docker-compose up -d
    - name: Deploy to production
      run: |
        ssh root@83.147.247.41 'cd lyftzeigen-spring-api/ && docker-compose pull && docker-compose up -d'